export const COLORS = {
  navy: '#1B2E4A',
  gold: '#D9A527',
  teal: '#1F6F5C',
  rust: '#B5423A',
  cream: '#F6F1E4',
  white: '#FFFFFF',
  lightGray: '#E8E0D0',
  muted: '#6B7A90',
};

export const STRINGS = {
  en: {
    onboarding1Title: 'Track Every Cedi',
    onboarding1Desc: 'Record sales and expenses in seconds, even offline.',
    onboarding2Title: 'Speak, Don’t Type',
    onboarding2Desc: 'Say “47.50 for Milo and bread” — AI does the rest.',
    onboarding3Title: 'Know Your Income',
    onboarding3Desc: 'Daily insights help you grow your shop, your way.',
    getStarted: 'Get Started',
    next: 'Next',
    skip: 'Skip',
    emailTitle: 'Welcome to CoreLedger',
    emailSubtitle: 'Sign in with your email to continue',
    emailPlaceholder: 'e.g. ama@example.com',
    passwordPlaceholder: 'Password (min 6 chars)',
    signIn: 'Sign In',
    signUp: 'Create Account',
    haveAccount: 'Already have an account? Sign In',
    noAccount: "Don't have an account? Sign Up",
    forgotPassword: 'Forgot password?',
    phoneTitle: 'Welcome to Ledger',
    phoneSubtitle: 'Enter your phone number to continue',
    phonePlaceholder: 'e.g. 024 123 4567',
    sendOTP: 'Send OTP',
    otpTitle: 'Verify your number',
    otpSubtitle: 'Enter the 4-digit code sent to your phone',
    verify: 'Verify',
    resend: 'Resend code',
    shopSetupTitle: 'Set up your shop',
    shopName: 'Shop Name',
    shopNamePlaceholder: 'e.g. Ama’s Provisions',
    shopCategory: 'Shop Category',
    dailyTarget: 'Daily Sales Target (GHS)',
    dailyTargetPlaceholder: 'e.g. 500',
    dailyTargetRequired: 'Optional — defaults to GHS 500 so AI can coach you',
    phone: 'Phone Number',
    saveAndContinue: 'Save & Continue',
    homeGreeting: 'Good morning',
    todaySales: "Today's Sales",
    todayExpenses: "Today's Expenses",
    todayProfit: "Today's Income",
    recordSale: 'Record Sale',
    recordExpense: 'Record Expense',
    aiInsight: 'AI Insight',
    recentTransactions: 'Recent Transactions',
    viewAll: 'View all',
    noTransactions: 'No transactions yet. Tap + to add one.',
    addSaleTitle: 'Record Sale',
    addExpenseTitle: 'Record Expense',
    amount: 'Amount (GHS)',
    description: 'Description',
    descriptionSalePlaceholder: 'e.g. Milo and bread',
    descriptionExpensePlaceholder: 'e.g. Transport fare',
    category: 'Category',
    paymentMethod: 'Payment Method',
    cash: 'Cash',
    momo: 'MoMo',
    credit: 'Credit',
    save: 'Save',
    cancel: 'Cancel',
    micHint: 'Tap mic and say amount & items',
    voiceParsed: 'AI parsed',
    ledgerTitle: 'Ledger',
    searchPlaceholder: 'Search transactions…',
    filterAll: 'All',
    filterSales: 'Sales',
    filterExpenses: 'Expenses',
    filterToday: 'Today',
    filterWeek: 'Week',
    filterMonth: 'Month',
    dailyTotal: 'Daily Total',
    reportsTitle: 'Reports',
    weekly: 'Weekly',
    monthly: 'Monthly',
    dailyProfit: 'Daily Income (GHS)',
    topCategories: 'Top Categories',
    insightTitle: 'AI Insight',
    insightFallback: 'Keep recording sales — your peak day will appear here once you have a few sales. AI will then show your true best day, not a fixed Saturday.',
    profileTitle: 'Profile',
    shopInfo: 'Shop Info',
    language: 'Language',
    english: 'English',
    twi: 'Twi (Akan)',
    exportCSV: 'Export as CSV',
    exported: 'CSV ready to share',
    signOut: 'Sign Out',
    edit: 'Edit',
  },
  tw: {
    onboarding1Title: 'Kyerɛw Cedi Biara',
    onboarding1Desc: 'Kyerɛw tɔn ne sika a wosɛe no ntɛm, mpo sɛ intanɛt nni hɔ.',
    onboarding2Title: 'Kasa, Nsɛm Nhyɛ',
    onboarding2Desc: 'Ka “47.50 ma Milo ne bread” — AI na ɛbɛyɛ nkae no.',
    onboarding3Title: 'Hu Mfaso a Wonya',
    onboarding3Desc: 'Nkyerɛkyerɛ da biara boa ma wo dwumadi nyin.',
    getStarted: 'Hyɛ aseɛ',
    next: 'Edi so',
    skip: 'Twa mu',
    emailTitle: 'Akwaaba ba CoreLedger',
    emailSubtitle: 'Fa wo email kɔ mu na yɛnkɔ so',
    emailPlaceholder: 'sɛ nhwɛso ama@example.com',
    passwordPlaceholder: 'Password (min 6)',
    signIn: 'Kɔ Mu',
    signUp: 'Yɛ Akawunt',
    haveAccount: 'Wo wɔ akawunt? Kɔ Mu',
    noAccount: 'Wonni akawunt? Yɛ Foforɔ',
    forgotPassword: 'Wo werɛ afi password?',
    phoneTitle: 'Akwaaba ba Ledger',
    phoneSubtitle: 'Hyɛ wo fon nɔma mu na yɛnkɔ so',
    phonePlaceholder: 'sɛ nhwɛso 024 123 4567',
    sendOTP: 'Mane OTP',
    otpTitle: 'Hwɛ wo nɔma mu',
    otpSubtitle: 'Hyɛ 4-digit code a yɛamane no mu',
    verify: 'Hwɛ mu',
    resend: 'Mane bio',
    shopSetupTitle: 'Siesie wo sotɔɔ',
    shopName: 'Sotɔɔ Din',
    shopNamePlaceholder: 'sɛ nhwɛso Ama’s Provisions',
    shopCategory: 'Sotɔɔ Korɔ',
    dailyTarget: 'Da Biara Aguadi Botae (GHS) *',
    dailyTargetPlaceholder: 'sɛ nhwɛso 500',
    dailyTargetRequired: 'Botae no ho hia (sɛ nhwɛso 500) na AI atumi akyerɛ wo',
    phone: 'Fon Nɔma',
    saveAndContinue: 'Sie na Kɔ So',
    homeGreeting: 'Maakye',
    todaySales: 'Nnɛ Tɔn',
    todayExpenses: 'Nnɛ Sɛe',
    todayProfit: 'Nnɛ Income',
    recordSale: 'Kyerɛw Tɔn',
    recordExpense: 'Kyerɛw Sɛe',
    aiInsight: 'AI Nhumu',
    recentTransactions: 'Nkyerɛw a Etwa To',
    viewAll: 'Hwɛ ne nyinaa',
    noTransactions: 'Nkyerɛw biara nni hɔ. Mia + na fa bi ka ho.',
    addSaleTitle: 'Kyerɛw Tɔn',
    addExpenseTitle: 'Kyerɛw Sɛe',
    amount: 'Sika Dodow (GHS)',
    description: 'Nkyerɛmu',
    descriptionSalePlaceholder: 'sɛ nhwɛso Milo ne bread',
    descriptionExpensePlaceholder: 'sɛ nhwɛso kar ka',
    category: 'Korɔ',
    paymentMethod: 'Akwan a Wotua So',
    cash: 'Nsa mu Sika',
    momo: 'MoMo',
    credit: 'Bosea',
    save: 'Sie',
    cancel: 'Gyae',
    micHint: 'Mia mic na ka sika ne nneɛma',
    voiceParsed: 'AI akyerɛw',
    ledgerTitle: 'Ledger',
    searchPlaceholder: 'Hwehwɛ nkyerɛw…',
    filterAll: 'Ne Nyinaa',
    filterSales: 'Tɔn',
    filterExpenses: 'Sɛe',
    filterToday: 'Ɛnnɛ',
    filterWeek: 'Dapɛn',
    filterMonth: 'Bosome',
    dailyTotal: 'Da Biara Dodow',
    reportsTitle: 'Amannɛbɔ',
    weekly: 'Dapɛn',
    monthly: 'Bosome',
    dailyProfit: 'Da Biara Income (GHS)',
    topCategories: 'Korɔ a Ɛkorɔn',
    insightTitle: 'AI Nhumu',
    insightFallback: 'Kyerɛw tɔn kakra — wo da a wotɔn kɔ soro no bɛda adi ha. AI bɛkyerɛ wo da pa no.',
    profileTitle: 'Profile',
    shopInfo: 'Sotɔɔ Ho Nsɛm',
    language: 'Kasa',
    english: 'English',
    twi: 'Twi (Akan)',
    exportCSV: 'Yi sɛ CSV',
    exported: 'CSV asiesie',
    signOut: 'Pue',
    edit: 'Sesa',
  },
};

export const SHOP_CATEGORIES = [
  'Provisions',
  'Fruits & Vegetables',
  'Food & Drink',
  'Cosmetics & Beauty',
  'Clothing & Fashion',
  'Electronics & Accessories',
  'Stationery & Books',
  'Pharmacy & Health',
  'Hardware & Tools',
  'Bakery & Confectionery',
  'Meat, Fish & Poultry',
  'General Merchandise',
  'Other',
];
export const SALE_CATEGORIES = ['Groceries','Drinks','Snacks','Household','Other'];
export const EXPENSE_CATEGORIES = ['Restock','Transport','Utilities','Packaging','Staff','Other'];
export const PAYMENT_METHODS = ['Cash','MoMo','Credit'];
export const INVENTORY_UNITS = ['pcs','kg','g','L','mL','box','pack','dozen','bag','roll'];
export const INVENTORY_CATEGORIES = ['Provisions','Drinks','Snacks','Household','Cosmetics','Electronics','Stationery','Clothing','Other'];

